[tool.poetry]
name = "tina4-python"
version = "0.2.38"
description = "Tina4Python - This is not another framework for Python"
authors = ["Andre van Zuydam <andrevanzuydam@gmail.com>"]
readme = "README.md"

[tool.poetry.scripts]

[tool.poetry.dependencies]
python = "^3.10"
Jinja2 = "^3.1.4"
mypy = "^0.991"
libsass = "^0.22.0"
python-dotenv = "^1.0.1"
pyjwt = "^2.8.0"
cryptography = "^42.0.5"
watchdog = "^4.0.0"
bcrypt = "^4.1.3"

[tool.poetry.group.dev.dependencies]
flake8 = "^7.0.0"
pytest = "^7.2.0"
jurigged = "^0.5.3"
safety = "^3.2.8"
ruff = "^0.7.0"
mysql-connector-python = "^9.1.0"
psycopg2-binary = "^2.9.10"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
